### ISSUE TITLE
Travis Build has failed due to cucumber-core:gherkin incompatibility

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/oneview-chef#398]
### Scenario/Intent
Travis Build has failed due to cucumber-core:gherkin incompatibility

### Expected Result
Build should pass without any errors

### Actual Result
$ rake test
rake aborted!
LoadError: cannot load such file -- cucumber/core/gherkin/tag_expression
/home/travis/.rvm/gems/ruby-2.4.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/travis/.rvm/gems/ruby-2.4.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/travis/.rvm/gems/ruby-2.4.4/gems/foodcritic-7.1.0/lib/foodcritic/domain.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.4/gems/foodcritic-7.1.0/lib/foodcritic.rb:10:in `require_relative'
/home/travis/.rvm/gems/ruby-2.4.4/gems/foodcritic-7.1.0/lib/foodcritic.rb:10:in `<top (required)>'
/home/travis/build/HewlettPackard/oneview-chef/Rakefile:16:in `require'
/home/travis/build/HewlettPackard/oneview-chef/Rakefile:16:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
The command "rake test" exited with 1.
0.54s$ bundle exec codeclimate-test-reporter
Coverage results not found
The command "bundle exec codeclimate-test-reporter" exited with 1.

**Comment by soodpr** [comment]
We can fix this by referring to below issue:
https://github.com/cucumber/cucumber/issues/483
