### ISSUE TITLE
Travis build is failing at multiple points due to incompatibilty between the dependencies

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/oneview-chef#401]
### Scenario/Intent
Travis build is failing at multiple points due to incompatibilty between the dependencies

### Environment Details
 - **oneview Cookbook Version:** 3.1.0
 - **OneView Version:** 5.10.0
 - **chef-client Version:** 14.14.29
 - **platform:** redhat

### Steps to Reproduce
Travis build fails for ruby 2.4, 2.5 but pass for 2.3.1

### Expected Result
Should be able to pass tests for 2.4 and 2.5

### Actual Result
No Chef resources found, skipping coverage calculation...

SimpleCov failed with exit 1
/home/travis/.rvm/rubies/ruby-2.4.6/bin/ruby -I/home/travis/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.1/lib:/home/travis/.rvm/gems/ruby-2.4.6/gems/rspec-support-3.9.2/lib /home/travis/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.1/exe/rspec --pattern spec/\*\*/\*_spec.rb --color  failed

The command "rake test" exited with 1.

1.00s$ bundle exec codeclimate-test-reporter

I, [2020-03-06T06:36:15.860550 #16801]  INFO -- : Reporting coverage data to Code Climate.

/home/travis/.rvm/gems/ruby-2.4.6/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:54:in `block in to_payload': undefined method `coverage' for #<SimpleCov::SourceFile:0x00000000026c4e20> (NoMethodError)

Did you mean?  coverage_data

	from /home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/forwardable.rb:229:in `map'

	from /home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/forwardable.rb:229:in `map'

	from /home/travis/.rvm/gems/ruby-2.4.6/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:41:in `to_payload'

	from /home/travis/.rvm/gems/ruby-2.4.6/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:27:in `format'

	from /home/travis/.rvm/gems/ruby-2.4.6/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter.rb:19:in `run'

	from /home/travis/.rvm/gems/ruby-2.4.6/gems/codeclimate-test-reporter-1.0.7/bin/codeclimate-test-reporter:21:in `<top (required)>'

	from /home/travis/.rvm/gems/ruby-2.4.6/bin/codeclimate-test-reporter:23:in `load'

	from /home/travis/.rvm/gems/ruby-2.4.6/bin/codeclimate-test-reporter:23:in `<main>'

	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'

	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'

The command "bundle exec codeclimate-test-reporter" exited with 1.

**Comment by soodpr** [comment]
closing this as it was fixed in above PR
